project:
  type: website
  output-dir: docs

website:
  title: "Bryant Ha's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Marketing_analytics.qmd 
        text: Marketing Analytics 
      - href: projects.qmd
        text: Projects
      - href: Digital_Marketing.qmd
        text: Digital Marketing
      - href: resume.qmd
        text: Resume
  page-footer:
    center: "© 2025 Bryant Ha"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true